package by.draughts.model.tournament;

public enum Rank {
    SECOND_CLASS_JUNIOR, FIRST_CLASS_JUNIOR, SECOND_CLASS, FIRST_CLASS,
    CANDIDATE_FOR_MASTER, MASTER, INTERNATIONAL_MASTER, GROSSMASTER
}
